In [9]:
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.simplefilter('ignore',DeprecationWarning)
arr=np.array([10,20,30,40,50])
arr_stand=(arr-arr.mean())/arr.std()
print(arr_stand)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [14]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit_transform(arr.reshape(-1,1))
scaler.fit_transform(arr.reshape(-1,1))

array([[-1.41421356],
       [-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356]])

In [17]:
from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()
min_max.fit_transform(arr.reshape(-1,1))

array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

In [43]:
import pandas as pd
from pandas import DataFrame
data={'Name':['Gokul','Minato','Naruto','Kira','Eren'],
      'Age':[20,40,25,25,20],
      'Height':[170,180,110,150,125],
      'Weight':[55,60,65,60,55],
      'BP':[0,100,65,70,40]}
frame=pd.DataFrame(data)
print('\n',frame)

frame.to_csv('paitent_data.csv',index=False)
df=pd.read_csv('paitent_data.csv')
print('\n',df)
df=df.replace(0, df.mean(numeric_only=True))
print('\n',df)
frame2=df[['Age','BP','Height','Weight']]
print('\n',frame2)
scaler.fit(frame2)
scaled=scaler.transform(frame2)
print('\n',scaled)
scaled.shape
print('\n','mean=%s' % scaled.mean(axis=0))
print('\n','standard deviation:%s'%scaled.std(axis=0))
frame3=df[['Age','BP','Height','Weight']]
min_max.fit(frame3)
scaled2=min_max.transform(frame3)
print('\n',scaled2)
print('\n','mean:%s'%scaled2.mean(axis=0))
print('\n','standard deviation:5s'%scaled2.std(axis=0))
from sklearn.feature_selection import VarianceThreshold 
sel=VarianceThreshold(threshold=(.5*(1-.9))
useful_features1 = sel.fit_transform(scaled)
print('\n','useful Feature values based on StandardScaler' )
print('\n',useful_features1)
useful_features2 = sel.fit_transform(scaled2)
print('\n','Useful feature values based on minmaxscaler')
print('\n',useful_features2)


SyntaxError: invalid syntax (1529217955.py, line 32)